security:
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: lespages_index
            logout:
                path:   the_logout
                target: accueil

    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }

    encoders:
          Symfony\Component\Security\Core\User\User: Plaintext